### ISSUE TITLE
English language strings are not available in AMOS

### ISSUE THREAD

**Issue by germanvaleroelizondo** [teruselearning/moodle-block_blcmodules#1]
Hi,

This plugin does not have its English language strings available in AMOS for translation into other languages.

The most likely cause is a coding error in 
$string['api_key_desc'] = 'If you are unsure where to get this, please refer to the <a href="https://blc.howcollege.ac.uk/blocks/scorm_package/guide.php">BLC Plugin Guide</a>.<br/> You can also test that your block is properly configured using <a href="'.$CFG->wwwroot.'/blocks/blc_modules/validate_settings.php">this tool</a>.';

Please see https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

**Comment by teruselearning** [comment]
> Hi,
> 
> This plugin does not have its English language strings available in AMOS for translation into other languages.
> 
> The most likely cause is a coding error in
> $string['api_key_desc'] = 'If you are unsure where to get this, please refer to the [BLC Plugin Guide](https://blc.howcollege.ac.uk/blocks/scorm_package/guide.php).
> You can also test that your block is properly configured using [this tool]('.$CFG->wwwroot.'/blocks/blc_modules/validate_settings.php).';
> 
> Please see https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

Hi germanvaleroelizondo,

We have now fixed this in the latest version to be committed shortly. Thank you for flagging it. 

Are you a BLC member college?

**Comment by germanvaleroelizondo** [comment]
Hi,
Thanks for fixing this issue.
I am a teacher of veterinary pathology at the largest mexican university. I am the main translator for the mexican Spanish language pack for Moodle.

**Comment by germanvaleroelizondo** [comment]
The plugin currently hosted at https://moodle.org/plugins/block_blc_modules still has not the English strings available for translation in AMOS.

**Comment by teruselearning** [comment]
Hi German,

This is because we are using some CFG variables in certain language
strings, which AMOS does not like.

Are you a BLC member college? If you are, I will create a fork without the
variables, so you and others are able to translate.

I believe all or most of the BLC member organisations are in the UK, or
other English speaking countries, and at this time all the resources
available through the plugin are in English, which is why this has not been
a requirement to date.

Best wishes,
Oliver

[image: Terus Elearning Logo]

Oliver Stearn
Director
Mobile:+447858230320
Website:https://terustechnology.co.uk
Email:oliver@teruselearning.co.uk
